remove "e.kind_of?(fatal)" from Job::Service#system_error? because the NameError occurs
this error occurs:
    NameError: undefined local variable or method `fatal' for main:Object