[wip] Rails 5.0.1
## Gemfile
gem "sprockets", "~> 3.5.0"
gem "sprockets-rails", "~> 3.0.0"

## sssion_store.rb (:mongoid_store)
	RuntimeError (#find_session not implemented.):
	rack (2.0.1) lib/rack/session/abstract/id.rb:380:in `find_session'
	rack (2.0.1) lib/rack/session/abstract/id.rb:270:in `load_session'
	actionpack (5.0.1) lib/action_dispatch/middleware/session/abstract_store.rb:56:in `block in load_session'
	actionpack (5.0.1) lib/action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
	actionpack (5.0.1) lib/action_dispatch/middleware/session/abstract_store.rb:56:in `load_session'

## view
undefined method `show_point?' for #<Article::Node::Page:0x00000019e24d48>
  app/helpers/opendata/list_helper.rb:26:in `block in render_page_list'
  app/helpers/opendata/list_helper.rb:15:in `render_page_list'
---
$ bin/rails app:update
    conflict  config/boot.rb
    conflict  config/routes.rb
    conflict  config/application.rb
    conflict  config/environment.rb
    conflict  config/secrets.yml
    conflict  config/environments/development.rb
    conflict  config/environments/production.rb
    conflict  config/environments/test.rb
    conflict  config/initializers/cookies_serializer.rb
    conflict  config/initializers/mime_types.rb
    conflict  config/initializers/session_store.rb
    conflict  config/initializers/wrap_parameters.rb
    conflict  config/locales/en.yml
    conflict  bin/rails
    conflict  bin/rake
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/new_framework_defaults.rb
      create  bin/setup
      create  bin/update